### ISSUE TITLE
Bad Regex

### ISSUE THREAD

**Issue by chinonin0** [BinaryShadow94/magicleaks#1]
Hay un error en la regex al comprobar el email en check_email(email).
	pattern = "(^[a-zA-Z-1-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
Los correos que empiecen por 0 no funcionarían.

**Comment by BinaryShadow94** [comment]
Se ha corregido la expresión regex, ya no debería dar error con aquellos correos que empiecen por 0.
